### ISSUE TITLE
New Task and Link Mode Shortcuts

### ISSUE THREAD

**Issue by KingTuning** [etrobert/taskgraph#6]
Add a short if it doesn't exist to add a task and create a shortcut that you have to hold pressed to change to link mode

**Comment by etrobert** [comment]
The shortcut to add a new task is currently **I**

The shortcut to add a link on desktop is currently Shift+Click on a Task+Drag to another Task

**Comment by etrobert** [comment]
I should add a page containing the shortcut lists at some points.
You can currently find them in the github repository under *doc/interface.md*
